[package]
name = "glow-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { workspace = true, features = ["tch", "autodiff", "dataset", "ndarray"] }
image = "*"
ndarray = "0.16.1"
ndarray-npz = "0.4.2"
serde = "1.0.219"
# tch = {workspace = true}
